services:
  backend:
    build:
      context: ./backend
      target: dev
    container_name: backend
    command: pipenv run start
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - database-dev

  database-dev:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "6543:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 6544:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - database-dev

volumes:
  pgadmin:
